"""empty message

Revision ID: 6c13b7915d3f
Revises: 
Create Date: 2023-04-21 11:13:45.351426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c13b7915d3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), server_default='Usuário', nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes',
    sa.Column('numero_cliente', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('nome_pais', sa.String(), nullable=True),
    sa.Column('nascimento', sa.String(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_cliente'),
    sa.UniqueConstraint('numero_cliente')
    )
    op.create_table('inversores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=False),
    sa.Column('potencia', sa.Integer(), nullable=False),
    sa.Column('overload', sa.Integer(), nullable=False),
    sa.Column('imp', sa.Float(), nullable=False),
    sa.Column('isc', sa.Float(), nullable=False),
    sa.Column('v_min_mppt', sa.Integer(), nullable=False),
    sa.Column('v_max_mppt', sa.Integer(), nullable=False),
    sa.Column('v_max', sa.Integer(), nullable=False),
    sa.Column('n_mppt', sa.Integer(), nullable=False),
    sa.Column('n_entrada', sa.Integer(), nullable=False),
    sa.Column('v_saida', sa.Integer(), nullable=False),
    sa.Column('i_saida', sa.Float(), nullable=False),
    sa.Column('eficiencia', sa.Float(), nullable=False),
    sa.Column('comprimento', sa.Float(), nullable=False),
    sa.Column('largura', sa.Float(), nullable=False),
    sa.Column('espessura', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modelo'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=False),
    sa.Column('potencia', sa.Integer(), nullable=False),
    sa.Column('imp', sa.Float(), nullable=False),
    sa.Column('isc', sa.Float(), nullable=False),
    sa.Column('vmp', sa.Float(), nullable=False),
    sa.Column('voc', sa.Float(), nullable=False),
    sa.Column('comprimento', sa.Float(), nullable=False),
    sa.Column('largura', sa.Float(), nullable=False),
    sa.Column('espessura', sa.Float(), nullable=False),
    sa.Column('eficiencia', sa.Float(), nullable=False),
    sa.Column('temperatura_nominal', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('coeficiente_temperatura', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modelo'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('instalacoes',
    sa.Column('numero_instalacao', sa.BigInteger(), nullable=False),
    sa.Column('numero_cliente', sa.BigInteger(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero_predial', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('classificacao', sa.String(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('coordenadas_decimais', sa.String(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numero_cliente'], ['clientes.numero_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_instalacao'),
    sa.UniqueConstraint('numero_instalacao')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('numero_instalacao', sa.BigInteger(), nullable=False),
    sa.Column('numero_cliente', sa.BigInteger(), nullable=False),
    sa.Column('ligacao_nova', sa.Boolean(), nullable=False),
    sa.Column('aumento_carga', sa.Boolean(), nullable=False),
    sa.Column('aumento_usina', sa.Boolean(), nullable=False),
    sa.Column('agrupamento', sa.Boolean(), nullable=False),
    sa.Column('n_fases', sa.String(), nullable=False),
    sa.Column('disjuntor', sa.Integer(), nullable=False),
    sa.Column('novo_n_fases', sa.String(), nullable=True),
    sa.Column('novo_disjuntor', sa.Integer(), nullable=True),
    sa.Column('n_fases_agrupamento', sa.String(), nullable=True),
    sa.Column('disjuntor_agrupamento', sa.Integer(), nullable=True),
    sa.Column('tensao', sa.Integer(), nullable=False),
    sa.Column('carga', sa.Float(), nullable=False),
    sa.Column('modulo_anterior_1', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('quantidade_modulo_1', sa.Integer(), nullable=False),
    sa.Column('modelo_modulo_1', sa.String(), nullable=False),
    sa.Column('potencia_modulo_1', sa.Integer(), nullable=False),
    sa.Column('modulo_anterior_2', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('quantidade_modulo_2', sa.Integer(), server_default='0', nullable=True),
    sa.Column('modelo_modulo_2', sa.String(), server_default='', nullable=True),
    sa.Column('potencia_modulo_2', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantidade_modulos', sa.Integer(), nullable=False),
    sa.Column('potencia_modulos_anterior', sa.Float(), nullable=True),
    sa.Column('potencia_modulos', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('inversor_anterior_1', sa.Boolean(), nullable=False),
    sa.Column('quantidade_inversor_1', sa.Integer(), nullable=False),
    sa.Column('modelo_inversor_1', sa.String(), nullable=False),
    sa.Column('potencia_inversor_1', sa.Integer(), nullable=False),
    sa.Column('inversor_anterior_2', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('quantidade_inversor_2', sa.Integer(), server_default='0', nullable=True),
    sa.Column('modelo_inversor_2', sa.String(), server_default='', nullable=True),
    sa.Column('potencia_inversor_2', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inversor_anterior_3', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('quantidade_inversor_3', sa.Integer(), server_default='0', nullable=True),
    sa.Column('modelo_inversor_3', sa.String(), server_default='', nullable=True),
    sa.Column('potencia_inversor_3', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inversor_anterior_4', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('quantidade_inversor_4', sa.Integer(), server_default='0', nullable=True),
    sa.Column('modelo_inversor_4', sa.String(), server_default='', nullable=True),
    sa.Column('potencia_inversor_4', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantidade_inversores', sa.Integer(), nullable=False),
    sa.Column('potencia_inversores_anterior', sa.Float(), nullable=True),
    sa.Column('potencia_inversores', sa.Float(), nullable=False),
    sa.Column('geracao_1', sa.Float(), nullable=False),
    sa.Column('geracao_2', sa.Float(), nullable=False),
    sa.Column('geracao_3', sa.Float(), nullable=False),
    sa.Column('geracao_4', sa.Float(), nullable=False),
    sa.Column('geracao_5', sa.Float(), nullable=False),
    sa.Column('geracao_6', sa.Float(), nullable=False),
    sa.Column('geracao_7', sa.Float(), nullable=False),
    sa.Column('geracao_8', sa.Float(), nullable=False),
    sa.Column('geracao_9', sa.Float(), nullable=False),
    sa.Column('geracao_10', sa.Float(), nullable=False),
    sa.Column('geracao_11', sa.Float(), nullable=False),
    sa.Column('geracao_12', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numero_cliente'], ['clientes.numero_cliente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numero_instalacao'], ['instalacoes.numero_instalacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetos')
    op.drop_table('instalacoes')
    op.drop_table('modulos')
    op.drop_table('inversores')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
